services:
  postgres:
    image: postgres:17
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypassword
    ports:
      - "5433:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

volumes:
  inventory_postgres_data: