spring.application.name=inventory-management-system1

# DATABASE CONFIGURATION
# URL
spring.datasource.url=jdbc:postgresql://localhost:5433/inventorydb?options=-c%20timezone=Europe/Kyiv

# Username
spring.datasource.username=inventoryuser

# Password.
spring.datasource.password=inventorypassword

# JDBC driver.
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / HIBERNATE CONFIGURATION
# Automatically update the database schema based on JPA entities.
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL queries in the application logs.
spring.jpa.show-sql=true

# Format generated SQL queries for better readability.
spring.jpa.properties.hibernate.format_sql=true

# Set the Hibernate JDBC timezone.
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Kyiv




# JWT CONFIGURATION
# EN: Secret key  to sign and verify JWT tokens.
jwt.secret=${JWT_SECRET}

# EN: JWT token lifetime 24 hours in milliseconds.
jwt.expiration=86400000